# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField()),
                ('questions_asked', models.CharField(max_length=200)),
                ('answers_given', models.CharField(max_length=200)),
            ],
        ),
    ]
