# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTree', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='survey_id',
        ),
    ]
